services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: cqrs_tp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/sql

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/cqrs_tp
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  pgdata:
